name: Deploy .NET 8 API

on:
  push:
    branches: [ master ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish API
        # Tìm tất cả file csproj và build, đẩy thẳng vào folder 'out' không chia thư mục con
        run: dotnet publish **/DevBlog.API.csproj -c Release -o out /p:UseAppHost=false

      - name: Verify Build (Debug)
        # Bước này để bạn kiểm tra xem file có tồn tại trong máy ảo GitHub không
        run: ls -R out

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/home/nhatdev/apps/api/publish"
          strip_components: 1
          overwrite: true
          rm: true 

      - name: Restart API Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Đảm bảo thư mục tồn tại và đúng quyền
            sudo chown -R root:root /home/nhatdev/apps/api/publish
            
            # Khởi động lại service
            sudo systemctl daemon-reload
            sudo systemctl restart devblog-api.service
            
            # Kiểm tra xem file đã xuất hiện chưa
            echo "Kiem tra file DLL trên VPS:"
            ls -l /home/nhatdev/apps/api/publish/DevBlog.API.dll
            
            # Xem trang thai service
            sleep 2
            sudo systemctl status devblog-api.service --no-pager