name: Deploy .NET 8 API

on:
  push:
    branches: [ master ] # <--- Kiểm tra xem là main hay master nhé

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish API
        run: dotnet publish -c Release -o ./out # Đổi tên folder đầu ra cho rõ ràng

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./out/*"
          target: "/home/nhatdev/apps/api/publish"
          strip_components: 1
          overwrite: true # Cho phép ghi đè file cũ

      - name: Restart API Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Đảm bảo quyền sở hữu đúng cho user (nếu cần)
            sudo chown -R root:root /home/nhatdev/apps/api/publish
            # Khởi động lại service
            sudo systemctl restart devblog-api.service