name: Deploy .NET 8 API

on:
  push:
    branches: [ master ] # Nếu sau này bạn đổi nhánh chính thành main thì nhớ sửa chỗ này

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish API
        # Dùng đường dẫn out cố định để dễ quản lý
        run: dotnet publish -c Release -o out

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/home/nhatdev/apps/api/publish"
          strip_components: 1
          overwrite: true
          # Xóa toàn bộ file cũ trong thư mục publish trước khi chép file mới 
          # để tránh xung đột file cũ/mới
          rm: true 

      - name: Restart API Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 1. Chuyển quyền sở hữu cho root (vì service chạy quyền root)
            sudo chown -R root:root /home/nhatdev/apps/api/publish
            
            # 2. Cấp quyền thực thi (nếu cần)
            sudo chmod +x /home/nhatdev/apps/api/publish/DevBlog.API.dll
            
            # 3. Khởi động lại service
            sudo systemctl restart devblog-api.service
            
            # 4. Đợi 2 giây rồi kiểm tra trạng thái xem có bị lỗi 'exit-code' nữa không
            sleep 2
            sudo systemctl status devblog-api.service --no-pager